# Generated by Django 4.0 on 2021-12-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loaner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('loan_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
