# Generated by Django 4.0 on 2021-12-11 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0002_loaner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loaner',
            old_name='name',
            new_name='text',
        ),
        migrations.AddField(
            model_name='game',
            name='loan_status',
            field=models.CharField(choices=[('A', 'available'), ('U', 'unavailable')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='loaner',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='board_games.game'),
            preserve_default=False,
        ),
    ]
