# Generated by Django 4.0 on 2021-12-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0003_rename_name_loaner_text_game_loan_status_loaner_game'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loaner',
            options={'verbose_name_plural': 'loaners'},
        ),
    ]
