# Generated by Django 4.0 on 2021-12-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0004_alter_loaner_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loaner',
            old_name='loan_time',
            new_name='date_added',
        ),
    ]
